// flow-typed signature: 7e3140ce8ffec147c0eab03df06a6389
// flow-typed version: <<STUB>>/cowsay-browser_v^1.1.8/flow_v0.75.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'cowsay-browser'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'cowsay-browser' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'cowsay-browser/build-cows' {
  declare module.exports: any;
}

declare module 'cowsay-browser/cli' {
  declare module.exports: any;
}

declare module 'cowsay-browser/lib/balloon' {
  declare module.exports: any;
}

declare module 'cowsay-browser/lib/cow-definitions' {
  declare module.exports: any;
}

declare module 'cowsay-browser/lib/cows' {
  declare module.exports: any;
}

declare module 'cowsay-browser/lib/faces' {
  declare module.exports: any;
}

declare module 'cowsay-browser/lib/replacer' {
  declare module.exports: any;
}

declare module 'cowsay-browser/test' {
  declare module.exports: any;
}

declare module 'cowsay-browser/test/balloon' {
  declare module.exports: any;
}

declare module 'cowsay-browser/test/cows' {
  declare module.exports: any;
}

declare module 'cowsay-browser/test/faces' {
  declare module.exports: any;
}

// Filename aliases
declare module 'cowsay-browser/build-cows.js' {
  declare module.exports: $Exports<'cowsay-browser/build-cows'>;
}
declare module 'cowsay-browser/cli.js' {
  declare module.exports: $Exports<'cowsay-browser/cli'>;
}
declare module 'cowsay-browser/index' {
  declare module.exports: $Exports<'cowsay-browser'>;
}
declare module 'cowsay-browser/index.js' {
  declare module.exports: $Exports<'cowsay-browser'>;
}
declare module 'cowsay-browser/lib/balloon.js' {
  declare module.exports: $Exports<'cowsay-browser/lib/balloon'>;
}
declare module 'cowsay-browser/lib/cow-definitions.js' {
  declare module.exports: $Exports<'cowsay-browser/lib/cow-definitions'>;
}
declare module 'cowsay-browser/lib/cows.js' {
  declare module.exports: $Exports<'cowsay-browser/lib/cows'>;
}
declare module 'cowsay-browser/lib/faces.js' {
  declare module.exports: $Exports<'cowsay-browser/lib/faces'>;
}
declare module 'cowsay-browser/lib/replacer.js' {
  declare module.exports: $Exports<'cowsay-browser/lib/replacer'>;
}
declare module 'cowsay-browser/test.js' {
  declare module.exports: $Exports<'cowsay-browser/test'>;
}
declare module 'cowsay-browser/test/balloon.js' {
  declare module.exports: $Exports<'cowsay-browser/test/balloon'>;
}
declare module 'cowsay-browser/test/cows.js' {
  declare module.exports: $Exports<'cowsay-browser/test/cows'>;
}
declare module 'cowsay-browser/test/faces.js' {
  declare module.exports: $Exports<'cowsay-browser/test/faces'>;
}
