// flow-typed signature: 2b1ca9c9c54928f35c11f12c5f905478
// flow-typed version: <<STUB>>/dotenv-webpack_v^1.5.4/flow_v0.68.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'dotenv-webpack'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'dotenv-webpack' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'dotenv-webpack/dist/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'dotenv-webpack/dist/index.js' {
  declare module.exports: $Exports<'dotenv-webpack/dist/index'>;
}
declare module 'dotenv-webpack/index' {
  declare module.exports: $Exports<'dotenv-webpack'>;
}
declare module 'dotenv-webpack/index.js' {
  declare module.exports: $Exports<'dotenv-webpack'>;
}
