// flow-typed signature: a4bab3883e5a1346243bd5cc65dc769b
// flow-typed version: <<STUB>>/eslint-plugin-relay_v^0.0.21/flow_v0.72.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'eslint-plugin-relay'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'eslint-plugin-relay' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'eslint-plugin-relay/eslint-plugin-relay' {
  declare module.exports: any;
}

declare module 'eslint-plugin-relay/src/rule-compat-uses-vars' {
  declare module.exports: any;
}

declare module 'eslint-plugin-relay/src/rule-generated-flow-types' {
  declare module.exports: any;
}

declare module 'eslint-plugin-relay/src/rule-graphql-naming' {
  declare module.exports: any;
}

declare module 'eslint-plugin-relay/src/rule-graphql-syntax' {
  declare module.exports: any;
}

declare module 'eslint-plugin-relay/src/utils' {
  declare module.exports: any;
}

// Filename aliases
declare module 'eslint-plugin-relay/eslint-plugin-relay.js' {
  declare module.exports: $Exports<'eslint-plugin-relay/eslint-plugin-relay'>;
}
declare module 'eslint-plugin-relay/src/rule-compat-uses-vars.js' {
  declare module.exports: $Exports<'eslint-plugin-relay/src/rule-compat-uses-vars'>;
}
declare module 'eslint-plugin-relay/src/rule-generated-flow-types.js' {
  declare module.exports: $Exports<'eslint-plugin-relay/src/rule-generated-flow-types'>;
}
declare module 'eslint-plugin-relay/src/rule-graphql-naming.js' {
  declare module.exports: $Exports<'eslint-plugin-relay/src/rule-graphql-naming'>;
}
declare module 'eslint-plugin-relay/src/rule-graphql-syntax.js' {
  declare module.exports: $Exports<'eslint-plugin-relay/src/rule-graphql-syntax'>;
}
declare module 'eslint-plugin-relay/src/utils.js' {
  declare module.exports: $Exports<'eslint-plugin-relay/src/utils'>;
}
