// flow-typed signature: b26fd2465f130b262dc7a96e200f1dc3
// flow-typed version: <<STUB>>/jest-puppeteer_v3.2.1/flow_v0.102.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'jest-puppeteer'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'jest-puppeteer' {
  declare module.exports: any;
}
