// flow-typed signature: e5381fb8931d7dddc0b83fa2e87ba00f
// flow-typed version: <<STUB>>/next_v^9.0.2/flow_v0.102.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'next'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'next' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'next/amp' {
  declare module.exports: any;
}

declare module 'next/app' {
  declare module.exports: any;
}

declare module 'next/babel' {
  declare module.exports: any;
}

declare module 'next/client' {
  declare module.exports: any;
}

declare module 'next/config' {
  declare module.exports: any;
}

declare module 'next/constants' {
  declare module.exports: any;
}

declare module 'next/data' {
  declare module.exports: any;
}

declare module 'next/dist/build/babel/plugins/amp-attributes' {
  declare module.exports: any;
}

declare module 'next/dist/build/babel/plugins/commonjs' {
  declare module.exports: any;
}

declare module 'next/dist/build/babel/plugins/next-data' {
  declare module.exports: any;
}

declare module 'next/dist/build/babel/plugins/next-page-config' {
  declare module.exports: any;
}

declare module 'next/dist/build/babel/plugins/react-loadable-plugin' {
  declare module.exports: any;
}

declare module 'next/dist/build/babel/preset' {
  declare module.exports: any;
}

declare module 'next/dist/build/compiler' {
  declare module.exports: any;
}

declare module 'next/dist/build/entries' {
  declare module.exports: any;
}

declare module 'next/dist/build/flying-shuttle' {
  declare module.exports: any;
}

declare module 'next/dist/build/generate-build-id' {
  declare module.exports: any;
}

declare module 'next/dist/build' {
  declare module.exports: any;
}

declare module 'next/dist/build/is-writeable' {
  declare module.exports: any;
}

declare module 'next/dist/build/output' {
  declare module.exports: any;
}

declare module 'next/dist/build/output/log' {
  declare module.exports: any;
}

declare module 'next/dist/build/output/store' {
  declare module.exports: any;
}

declare module 'next/dist/build/static-checker' {
  declare module.exports: any;
}

declare module 'next/dist/build/utils' {
  declare module.exports: any;
}

declare module 'next/dist/build/webpack-config' {
  declare module.exports: any;
}

declare module 'next/dist/build/webpack/loaders/emit-file-loader' {
  declare module.exports: any;
}

declare module 'next/dist/build/webpack/loaders/next-babel-loader' {
  declare module.exports: any;
}

declare module 'next/dist/build/webpack/loaders/next-client-pages-loader' {
  declare module.exports: any;
}

declare module 'next/dist/build/webpack/loaders/next-data-loader' {
  declare module.exports: any;
}

declare module 'next/dist/build/webpack/loaders/next-minify-loader' {
  declare module.exports: any;
}

declare module 'next/dist/build/webpack/loaders/next-serverless-loader' {
  declare module.exports: any;
}

declare module 'next/dist/build/webpack/loaders/noop-loader' {
  declare module.exports: any;
}

declare module 'next/dist/build/webpack/plugins/all-modules-identified-plugin' {
  declare module.exports: any;
}

declare module 'next/dist/build/webpack/plugins/build-manifest-plugin' {
  declare module.exports: any;
}

declare module 'next/dist/build/webpack/plugins/chunk-graph-plugin' {
  declare module.exports: any;
}

declare module 'next/dist/build/webpack/plugins/chunk-names-plugin' {
  declare module.exports: any;
}

declare module 'next/dist/build/webpack/plugins/dll-import' {
  declare module.exports: any;
}

declare module 'next/dist/build/webpack/plugins/hashed-chunk-ids-plugin' {
  declare module.exports: any;
}

declare module 'next/dist/build/webpack/plugins/next-drop-client-page-plugin' {
  declare module.exports: any;
}

declare module 'next/dist/build/webpack/plugins/nextjs-require-cache-hot-reloader' {
  declare module.exports: any;
}

declare module 'next/dist/build/webpack/plugins/nextjs-ssr-import' {
  declare module.exports: any;
}

declare module 'next/dist/build/webpack/plugins/nextjs-ssr-module-cache' {
  declare module.exports: any;
}

declare module 'next/dist/build/webpack/plugins/pages-manifest-plugin' {
  declare module.exports: any;
}

declare module 'next/dist/build/webpack/plugins/react-loadable-plugin' {
  declare module.exports: any;
}

declare module 'next/dist/build/webpack/plugins/serverless-plugin' {
  declare module.exports: any;
}

declare module 'next/dist/build/webpack/plugins/shared-runtime-plugin' {
  declare module.exports: any;
}

declare module 'next/dist/build/webpack/plugins/terser-webpack-plugin/src' {
  declare module.exports: any;
}

declare module 'next/dist/build/webpack/plugins/terser-webpack-plugin/src/minify' {
  declare module.exports: any;
}

declare module 'next/dist/build/webpack/plugins/terser-webpack-plugin/src/TaskRunner' {
  declare module.exports: any;
}

declare module 'next/dist/build/webpack/plugins/terser-webpack-plugin/src/worker' {
  declare module.exports: any;
}

declare module 'next/dist/build/webpack/plugins/unlink-removed-pages-plugin' {
  declare module.exports: any;
}

declare module 'next/dist/build/write-build-id' {
  declare module.exports: any;
}

declare module 'next/dist/cli/next-build' {
  declare module.exports: any;
}

declare module 'next/dist/cli/next-dev' {
  declare module.exports: any;
}

declare module 'next/dist/cli/next-export' {
  declare module.exports: any;
}

declare module 'next/dist/cli/next-start' {
  declare module.exports: any;
}

declare module 'next/dist/client/dev/amp-dev' {
  declare module.exports: any;
}

declare module 'next/dist/client/dev/dev-build-watcher' {
  declare module.exports: any;
}

declare module 'next/dist/client/dev/error-overlay/eventsource' {
  declare module.exports: any;
}

declare module 'next/dist/client/dev/error-overlay/format-webpack-messages' {
  declare module.exports: any;
}

declare module 'next/dist/client/dev/error-overlay/hot-dev-client' {
  declare module.exports: any;
}

declare module 'next/dist/client/dev/error-overlay/source-map-support' {
  declare module.exports: any;
}

declare module 'next/dist/client/dev/event-source-polyfill' {
  declare module.exports: any;
}

declare module 'next/dist/client/dev/noop' {
  declare module.exports: any;
}

declare module 'next/dist/client/dev/on-demand-entries-client' {
  declare module.exports: any;
}

declare module 'next/dist/client/dev/on-demand-entries-utils' {
  declare module.exports: any;
}

declare module 'next/dist/client/dev/prerender-indicator' {
  declare module.exports: any;
}

declare module 'next/dist/client/dev/webpack-hot-middleware-client' {
  declare module.exports: any;
}

declare module 'next/dist/client/head-manager' {
  declare module.exports: any;
}

declare module 'next/dist/client' {
  declare module.exports: any;
}

declare module 'next/dist/client/link' {
  declare module.exports: any;
}

declare module 'next/dist/client/next-dev' {
  declare module.exports: any;
}

declare module 'next/dist/client/next' {
  declare module.exports: any;
}

declare module 'next/dist/client/page-loader' {
  declare module.exports: any;
}

declare module 'next/dist/client/router' {
  declare module.exports: any;
}

declare module 'next/dist/client/with-router' {
  declare module.exports: any;
}

declare module 'next/dist/compiled/arg' {
  declare module.exports: any;
}

declare module 'next/dist/compiled/nanoid' {
  declare module.exports: any;
}

declare module 'next/dist/compiled/resolve' {
  declare module.exports: any;
}

declare module 'next/dist/compiled/text-table' {
  declare module.exports: any;
}

declare module 'next/dist/compiled/unistore/unistore' {
  declare module.exports: any;
}

declare module 'next/dist/export' {
  declare module.exports: any;
}

declare module 'next/dist/export/worker' {
  declare module.exports: any;
}

declare module 'next/dist/lib/constants' {
  declare module.exports: any;
}

declare module 'next/dist/lib/data' {
  declare module.exports: any;
}

declare module 'next/dist/lib/pretty-bytes' {
  declare module.exports: any;
}

declare module 'next/dist/lib/recursive-copy' {
  declare module.exports: any;
}

declare module 'next/dist/lib/recursive-delete' {
  declare module.exports: any;
}

declare module 'next/dist/lib/recursive-readdir' {
  declare module.exports: any;
}

declare module 'next/dist/lib/verifyTypeScriptSetup' {
  declare module.exports: any;
}

declare module 'next/dist/pages/_app' {
  declare module.exports: any;
}

declare module 'next/dist/pages/_document' {
  declare module.exports: any;
}

declare module 'next/dist/pages/_error' {
  declare module.exports: any;
}

declare module 'next/dist/server/error-debug' {
  declare module.exports: any;
}

declare module 'next/dist/server/hot-reloader' {
  declare module.exports: any;
}

declare module 'next/dist/server/htmlescape' {
  declare module.exports: any;
}

declare module 'next/dist/server/lib/error-overlay-middleware' {
  declare module.exports: any;
}

declare module 'next/dist/server/lib/find-page-file' {
  declare module.exports: any;
}

declare module 'next/dist/server/lib/start-server' {
  declare module.exports: any;
}

declare module 'next/dist/server/lib/utils' {
  declare module.exports: any;
}

declare module 'next/dist/server/next-dev-server' {
  declare module.exports: any;
}

declare module 'next/dist/server/next' {
  declare module.exports: any;
}

declare module 'next/dist/server/on-demand-entry-handler' {
  declare module.exports: any;
}

declare module 'next/document' {
  declare module.exports: any;
}

declare module 'next/dynamic' {
  declare module.exports: any;
}

declare module 'next/error' {
  declare module.exports: any;
}

declare module 'next/head' {
  declare module.exports: any;
}

declare module 'next/link' {
  declare module.exports: any;
}

declare module 'next/router' {
  declare module.exports: any;
}

// Filename aliases
declare module 'next/amp.js' {
  declare module.exports: $Exports<'next/amp'>;
}
declare module 'next/app.js' {
  declare module.exports: $Exports<'next/app'>;
}
declare module 'next/babel.js' {
  declare module.exports: $Exports<'next/babel'>;
}
declare module 'next/client.js' {
  declare module.exports: $Exports<'next/client'>;
}
declare module 'next/config.js' {
  declare module.exports: $Exports<'next/config'>;
}
declare module 'next/constants.js' {
  declare module.exports: $Exports<'next/constants'>;
}
declare module 'next/data.js' {
  declare module.exports: $Exports<'next/data'>;
}
declare module 'next/dist/build/babel/plugins/amp-attributes.js' {
  declare module.exports: $Exports<'next/dist/build/babel/plugins/amp-attributes'>;
}
declare module 'next/dist/build/babel/plugins/commonjs.js' {
  declare module.exports: $Exports<'next/dist/build/babel/plugins/commonjs'>;
}
declare module 'next/dist/build/babel/plugins/next-data.js' {
  declare module.exports: $Exports<'next/dist/build/babel/plugins/next-data'>;
}
declare module 'next/dist/build/babel/plugins/next-page-config.js' {
  declare module.exports: $Exports<'next/dist/build/babel/plugins/next-page-config'>;
}
declare module 'next/dist/build/babel/plugins/react-loadable-plugin.js' {
  declare module.exports: $Exports<'next/dist/build/babel/plugins/react-loadable-plugin'>;
}
declare module 'next/dist/build/babel/preset.js' {
  declare module.exports: $Exports<'next/dist/build/babel/preset'>;
}
declare module 'next/dist/build/compiler.js' {
  declare module.exports: $Exports<'next/dist/build/compiler'>;
}
declare module 'next/dist/build/entries.js' {
  declare module.exports: $Exports<'next/dist/build/entries'>;
}
declare module 'next/dist/build/flying-shuttle.js' {
  declare module.exports: $Exports<'next/dist/build/flying-shuttle'>;
}
declare module 'next/dist/build/generate-build-id.js' {
  declare module.exports: $Exports<'next/dist/build/generate-build-id'>;
}
declare module 'next/dist/build/index' {
  declare module.exports: $Exports<'next/dist/build'>;
}
declare module 'next/dist/build/index.js' {
  declare module.exports: $Exports<'next/dist/build'>;
}
declare module 'next/dist/build/is-writeable.js' {
  declare module.exports: $Exports<'next/dist/build/is-writeable'>;
}
declare module 'next/dist/build/output/index' {
  declare module.exports: $Exports<'next/dist/build/output'>;
}
declare module 'next/dist/build/output/index.js' {
  declare module.exports: $Exports<'next/dist/build/output'>;
}
declare module 'next/dist/build/output/log.js' {
  declare module.exports: $Exports<'next/dist/build/output/log'>;
}
declare module 'next/dist/build/output/store.js' {
  declare module.exports: $Exports<'next/dist/build/output/store'>;
}
declare module 'next/dist/build/static-checker.js' {
  declare module.exports: $Exports<'next/dist/build/static-checker'>;
}
declare module 'next/dist/build/utils.js' {
  declare module.exports: $Exports<'next/dist/build/utils'>;
}
declare module 'next/dist/build/webpack-config.js' {
  declare module.exports: $Exports<'next/dist/build/webpack-config'>;
}
declare module 'next/dist/build/webpack/loaders/emit-file-loader.js' {
  declare module.exports: $Exports<'next/dist/build/webpack/loaders/emit-file-loader'>;
}
declare module 'next/dist/build/webpack/loaders/next-babel-loader.js' {
  declare module.exports: $Exports<'next/dist/build/webpack/loaders/next-babel-loader'>;
}
declare module 'next/dist/build/webpack/loaders/next-client-pages-loader.js' {
  declare module.exports: $Exports<'next/dist/build/webpack/loaders/next-client-pages-loader'>;
}
declare module 'next/dist/build/webpack/loaders/next-data-loader.js' {
  declare module.exports: $Exports<'next/dist/build/webpack/loaders/next-data-loader'>;
}
declare module 'next/dist/build/webpack/loaders/next-minify-loader.js' {
  declare module.exports: $Exports<'next/dist/build/webpack/loaders/next-minify-loader'>;
}
declare module 'next/dist/build/webpack/loaders/next-serverless-loader.js' {
  declare module.exports: $Exports<'next/dist/build/webpack/loaders/next-serverless-loader'>;
}
declare module 'next/dist/build/webpack/loaders/noop-loader.js' {
  declare module.exports: $Exports<'next/dist/build/webpack/loaders/noop-loader'>;
}
declare module 'next/dist/build/webpack/plugins/all-modules-identified-plugin.js' {
  declare module.exports: $Exports<'next/dist/build/webpack/plugins/all-modules-identified-plugin'>;
}
declare module 'next/dist/build/webpack/plugins/build-manifest-plugin.js' {
  declare module.exports: $Exports<'next/dist/build/webpack/plugins/build-manifest-plugin'>;
}
declare module 'next/dist/build/webpack/plugins/chunk-graph-plugin.js' {
  declare module.exports: $Exports<'next/dist/build/webpack/plugins/chunk-graph-plugin'>;
}
declare module 'next/dist/build/webpack/plugins/chunk-names-plugin.js' {
  declare module.exports: $Exports<'next/dist/build/webpack/plugins/chunk-names-plugin'>;
}
declare module 'next/dist/build/webpack/plugins/dll-import.js' {
  declare module.exports: $Exports<'next/dist/build/webpack/plugins/dll-import'>;
}
declare module 'next/dist/build/webpack/plugins/hashed-chunk-ids-plugin.js' {
  declare module.exports: $Exports<'next/dist/build/webpack/plugins/hashed-chunk-ids-plugin'>;
}
declare module 'next/dist/build/webpack/plugins/next-drop-client-page-plugin.js' {
  declare module.exports: $Exports<'next/dist/build/webpack/plugins/next-drop-client-page-plugin'>;
}
declare module 'next/dist/build/webpack/plugins/nextjs-require-cache-hot-reloader.js' {
  declare module.exports: $Exports<'next/dist/build/webpack/plugins/nextjs-require-cache-hot-reloader'>;
}
declare module 'next/dist/build/webpack/plugins/nextjs-ssr-import.js' {
  declare module.exports: $Exports<'next/dist/build/webpack/plugins/nextjs-ssr-import'>;
}
declare module 'next/dist/build/webpack/plugins/nextjs-ssr-module-cache.js' {
  declare module.exports: $Exports<'next/dist/build/webpack/plugins/nextjs-ssr-module-cache'>;
}
declare module 'next/dist/build/webpack/plugins/pages-manifest-plugin.js' {
  declare module.exports: $Exports<'next/dist/build/webpack/plugins/pages-manifest-plugin'>;
}
declare module 'next/dist/build/webpack/plugins/react-loadable-plugin.js' {
  declare module.exports: $Exports<'next/dist/build/webpack/plugins/react-loadable-plugin'>;
}
declare module 'next/dist/build/webpack/plugins/serverless-plugin.js' {
  declare module.exports: $Exports<'next/dist/build/webpack/plugins/serverless-plugin'>;
}
declare module 'next/dist/build/webpack/plugins/shared-runtime-plugin.js' {
  declare module.exports: $Exports<'next/dist/build/webpack/plugins/shared-runtime-plugin'>;
}
declare module 'next/dist/build/webpack/plugins/terser-webpack-plugin/src/index' {
  declare module.exports: $Exports<'next/dist/build/webpack/plugins/terser-webpack-plugin/src'>;
}
declare module 'next/dist/build/webpack/plugins/terser-webpack-plugin/src/index.js' {
  declare module.exports: $Exports<'next/dist/build/webpack/plugins/terser-webpack-plugin/src'>;
}
declare module 'next/dist/build/webpack/plugins/terser-webpack-plugin/src/minify.js' {
  declare module.exports: $Exports<'next/dist/build/webpack/plugins/terser-webpack-plugin/src/minify'>;
}
declare module 'next/dist/build/webpack/plugins/terser-webpack-plugin/src/TaskRunner.js' {
  declare module.exports: $Exports<'next/dist/build/webpack/plugins/terser-webpack-plugin/src/TaskRunner'>;
}
declare module 'next/dist/build/webpack/plugins/terser-webpack-plugin/src/worker.js' {
  declare module.exports: $Exports<'next/dist/build/webpack/plugins/terser-webpack-plugin/src/worker'>;
}
declare module 'next/dist/build/webpack/plugins/unlink-removed-pages-plugin.js' {
  declare module.exports: $Exports<'next/dist/build/webpack/plugins/unlink-removed-pages-plugin'>;
}
declare module 'next/dist/build/write-build-id.js' {
  declare module.exports: $Exports<'next/dist/build/write-build-id'>;
}
declare module 'next/dist/cli/next-build.js' {
  declare module.exports: $Exports<'next/dist/cli/next-build'>;
}
declare module 'next/dist/cli/next-dev.js' {
  declare module.exports: $Exports<'next/dist/cli/next-dev'>;
}
declare module 'next/dist/cli/next-export.js' {
  declare module.exports: $Exports<'next/dist/cli/next-export'>;
}
declare module 'next/dist/cli/next-start.js' {
  declare module.exports: $Exports<'next/dist/cli/next-start'>;
}
declare module 'next/dist/client/dev/amp-dev.js' {
  declare module.exports: $Exports<'next/dist/client/dev/amp-dev'>;
}
declare module 'next/dist/client/dev/dev-build-watcher.js' {
  declare module.exports: $Exports<'next/dist/client/dev/dev-build-watcher'>;
}
declare module 'next/dist/client/dev/error-overlay/eventsource.js' {
  declare module.exports: $Exports<'next/dist/client/dev/error-overlay/eventsource'>;
}
declare module 'next/dist/client/dev/error-overlay/format-webpack-messages.js' {
  declare module.exports: $Exports<'next/dist/client/dev/error-overlay/format-webpack-messages'>;
}
declare module 'next/dist/client/dev/error-overlay/hot-dev-client.js' {
  declare module.exports: $Exports<'next/dist/client/dev/error-overlay/hot-dev-client'>;
}
declare module 'next/dist/client/dev/error-overlay/source-map-support.js' {
  declare module.exports: $Exports<'next/dist/client/dev/error-overlay/source-map-support'>;
}
declare module 'next/dist/client/dev/event-source-polyfill.js' {
  declare module.exports: $Exports<'next/dist/client/dev/event-source-polyfill'>;
}
declare module 'next/dist/client/dev/noop.js' {
  declare module.exports: $Exports<'next/dist/client/dev/noop'>;
}
declare module 'next/dist/client/dev/on-demand-entries-client.js' {
  declare module.exports: $Exports<'next/dist/client/dev/on-demand-entries-client'>;
}
declare module 'next/dist/client/dev/on-demand-entries-utils.js' {
  declare module.exports: $Exports<'next/dist/client/dev/on-demand-entries-utils'>;
}
declare module 'next/dist/client/dev/prerender-indicator.js' {
  declare module.exports: $Exports<'next/dist/client/dev/prerender-indicator'>;
}
declare module 'next/dist/client/dev/webpack-hot-middleware-client.js' {
  declare module.exports: $Exports<'next/dist/client/dev/webpack-hot-middleware-client'>;
}
declare module 'next/dist/client/head-manager.js' {
  declare module.exports: $Exports<'next/dist/client/head-manager'>;
}
declare module 'next/dist/client/index' {
  declare module.exports: $Exports<'next/dist/client'>;
}
declare module 'next/dist/client/index.js' {
  declare module.exports: $Exports<'next/dist/client'>;
}
declare module 'next/dist/client/link.js' {
  declare module.exports: $Exports<'next/dist/client/link'>;
}
declare module 'next/dist/client/next-dev.js' {
  declare module.exports: $Exports<'next/dist/client/next-dev'>;
}
declare module 'next/dist/client/next.js' {
  declare module.exports: $Exports<'next/dist/client/next'>;
}
declare module 'next/dist/client/page-loader.js' {
  declare module.exports: $Exports<'next/dist/client/page-loader'>;
}
declare module 'next/dist/client/router.js' {
  declare module.exports: $Exports<'next/dist/client/router'>;
}
declare module 'next/dist/client/with-router.js' {
  declare module.exports: $Exports<'next/dist/client/with-router'>;
}
declare module 'next/dist/compiled/arg/index' {
  declare module.exports: $Exports<'next/dist/compiled/arg'>;
}
declare module 'next/dist/compiled/arg/index.js' {
  declare module.exports: $Exports<'next/dist/compiled/arg'>;
}
declare module 'next/dist/compiled/nanoid/index' {
  declare module.exports: $Exports<'next/dist/compiled/nanoid'>;
}
declare module 'next/dist/compiled/nanoid/index.js' {
  declare module.exports: $Exports<'next/dist/compiled/nanoid'>;
}
declare module 'next/dist/compiled/resolve/index' {
  declare module.exports: $Exports<'next/dist/compiled/resolve'>;
}
declare module 'next/dist/compiled/resolve/index.js' {
  declare module.exports: $Exports<'next/dist/compiled/resolve'>;
}
declare module 'next/dist/compiled/text-table/index' {
  declare module.exports: $Exports<'next/dist/compiled/text-table'>;
}
declare module 'next/dist/compiled/text-table/index.js' {
  declare module.exports: $Exports<'next/dist/compiled/text-table'>;
}
declare module 'next/dist/compiled/unistore/unistore.js' {
  declare module.exports: $Exports<'next/dist/compiled/unistore/unistore'>;
}
declare module 'next/dist/export/index' {
  declare module.exports: $Exports<'next/dist/export'>;
}
declare module 'next/dist/export/index.js' {
  declare module.exports: $Exports<'next/dist/export'>;
}
declare module 'next/dist/export/worker.js' {
  declare module.exports: $Exports<'next/dist/export/worker'>;
}
declare module 'next/dist/lib/constants.js' {
  declare module.exports: $Exports<'next/dist/lib/constants'>;
}
declare module 'next/dist/lib/data.js' {
  declare module.exports: $Exports<'next/dist/lib/data'>;
}
declare module 'next/dist/lib/pretty-bytes.js' {
  declare module.exports: $Exports<'next/dist/lib/pretty-bytes'>;
}
declare module 'next/dist/lib/recursive-copy.js' {
  declare module.exports: $Exports<'next/dist/lib/recursive-copy'>;
}
declare module 'next/dist/lib/recursive-delete.js' {
  declare module.exports: $Exports<'next/dist/lib/recursive-delete'>;
}
declare module 'next/dist/lib/recursive-readdir.js' {
  declare module.exports: $Exports<'next/dist/lib/recursive-readdir'>;
}
declare module 'next/dist/lib/verifyTypeScriptSetup.js' {
  declare module.exports: $Exports<'next/dist/lib/verifyTypeScriptSetup'>;
}
declare module 'next/dist/pages/_app.js' {
  declare module.exports: $Exports<'next/dist/pages/_app'>;
}
declare module 'next/dist/pages/_document.js' {
  declare module.exports: $Exports<'next/dist/pages/_document'>;
}
declare module 'next/dist/pages/_error.js' {
  declare module.exports: $Exports<'next/dist/pages/_error'>;
}
declare module 'next/dist/server/error-debug.js' {
  declare module.exports: $Exports<'next/dist/server/error-debug'>;
}
declare module 'next/dist/server/hot-reloader.js' {
  declare module.exports: $Exports<'next/dist/server/hot-reloader'>;
}
declare module 'next/dist/server/htmlescape.js' {
  declare module.exports: $Exports<'next/dist/server/htmlescape'>;
}
declare module 'next/dist/server/lib/error-overlay-middleware.js' {
  declare module.exports: $Exports<'next/dist/server/lib/error-overlay-middleware'>;
}
declare module 'next/dist/server/lib/find-page-file.js' {
  declare module.exports: $Exports<'next/dist/server/lib/find-page-file'>;
}
declare module 'next/dist/server/lib/start-server.js' {
  declare module.exports: $Exports<'next/dist/server/lib/start-server'>;
}
declare module 'next/dist/server/lib/utils.js' {
  declare module.exports: $Exports<'next/dist/server/lib/utils'>;
}
declare module 'next/dist/server/next-dev-server.js' {
  declare module.exports: $Exports<'next/dist/server/next-dev-server'>;
}
declare module 'next/dist/server/next.js' {
  declare module.exports: $Exports<'next/dist/server/next'>;
}
declare module 'next/dist/server/on-demand-entry-handler.js' {
  declare module.exports: $Exports<'next/dist/server/on-demand-entry-handler'>;
}
declare module 'next/document.js' {
  declare module.exports: $Exports<'next/document'>;
}
declare module 'next/dynamic.js' {
  declare module.exports: $Exports<'next/dynamic'>;
}
declare module 'next/error.js' {
  declare module.exports: $Exports<'next/error'>;
}
declare module 'next/head.js' {
  declare module.exports: $Exports<'next/head'>;
}
declare module 'next/link.js' {
  declare module.exports: $Exports<'next/link'>;
}
declare module 'next/router.js' {
  declare module.exports: $Exports<'next/router'>;
}
