// flow-typed signature: 97adc8e7b2801198c47cc769caa4873f
// flow-typed version: <<STUB>>/react-countdown-now_v^1.3.0/flow_v0.84.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-countdown-now'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-countdown-now' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-countdown-now/dist/Countdown' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-countdown-now/dist/Countdown.js' {
  declare module.exports: $Exports<'react-countdown-now/dist/Countdown'>;
}
