// flow-typed signature: 0e9dde5d2815d2e37a82262d8b94ebea
// flow-typed version: <<STUB>>/react-hamburger-menu_v^1.1.1/flow_v0.94.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-hamburger-menu'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-hamburger-menu' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-hamburger-menu/dist/HamburgerMenu' {
  declare module.exports: any;
}

declare module 'react-hamburger-menu/dist/react-hamburger-menu.min' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-hamburger-menu/dist/HamburgerMenu.js' {
  declare module.exports: $Exports<'react-hamburger-menu/dist/HamburgerMenu'>;
}
declare module 'react-hamburger-menu/dist/react-hamburger-menu.min.js' {
  declare module.exports: $Exports<'react-hamburger-menu/dist/react-hamburger-menu.min'>;
}
