// flow-typed signature: 617f988f7c1efce3455682334f7799be
// flow-typed version: <<STUB>>/react-countdown-now_v^2.1.1/flow_v0.102.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-countdown-now'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-countdown-now' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-countdown-now/dist/index.es' {
  declare module.exports: any;
}

declare module 'react-countdown-now/dist' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-countdown-now/dist/index.es.js' {
  declare module.exports: $Exports<'react-countdown-now/dist/index.es'>;
}
declare module 'react-countdown-now/dist/index' {
  declare module.exports: $Exports<'react-countdown-now/dist'>;
}
declare module 'react-countdown-now/dist/index.js' {
  declare module.exports: $Exports<'react-countdown-now/dist'>;
}
