// flow-typed signature: 930a5445941fcb4729f5d079de3d3747
// flow-typed version: <<STUB>>/styled-flex-component_v^2.2.2/flow_v0.86.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'styled-flex-component'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'styled-flex-component' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'styled-flex-component/dist/styled-flex-component.es' {
  declare module.exports: any;
}

declare module 'styled-flex-component/dist/styled-flex-component.iife' {
  declare module.exports: any;
}

declare module 'styled-flex-component/dist/styled-flex-component.umd' {
  declare module.exports: any;
}

// Filename aliases
declare module 'styled-flex-component/dist/styled-flex-component.es.js' {
  declare module.exports: $Exports<'styled-flex-component/dist/styled-flex-component.es'>;
}
declare module 'styled-flex-component/dist/styled-flex-component.iife.js' {
  declare module.exports: $Exports<'styled-flex-component/dist/styled-flex-component.iife'>;
}
declare module 'styled-flex-component/dist/styled-flex-component.umd.js' {
  declare module.exports: $Exports<'styled-flex-component/dist/styled-flex-component.umd'>;
}
