// flow-typed signature: a4b6a5fd0802d06007c7edb360876aea
// flow-typed version: <<STUB>>/video-react_v^0.14.0/flow_v0.102.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'video-react'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'video-react' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'video-react/dist/video-react.cjs' {
  declare module.exports: any;
}

declare module 'video-react/dist/video-react.es' {
  declare module.exports: any;
}

declare module 'video-react/dist/video-react.full' {
  declare module.exports: any;
}

declare module 'video-react/dist/video-react.full.min' {
  declare module.exports: any;
}

declare module 'video-react/dist/video-react' {
  declare module.exports: any;
}

declare module 'video-react/dist/video-react.min' {
  declare module.exports: any;
}

declare module 'video-react/lib/actions/player' {
  declare module.exports: any;
}

declare module 'video-react/lib/actions/video' {
  declare module.exports: any;
}

declare module 'video-react/lib/components/Bezel' {
  declare module.exports: any;
}

declare module 'video-react/lib/components/BigPlayButton' {
  declare module.exports: any;
}

declare module 'video-react/lib/components/ClickableComponent' {
  declare module.exports: any;
}

declare module 'video-react/lib/components/control-bar/ClosedCaptionButton' {
  declare module.exports: any;
}

declare module 'video-react/lib/components/control-bar/ControlBar' {
  declare module.exports: any;
}

declare module 'video-react/lib/components/control-bar/ForwardControl' {
  declare module.exports: any;
}

declare module 'video-react/lib/components/control-bar/ForwardReplayControl' {
  declare module.exports: any;
}

declare module 'video-react/lib/components/control-bar/FullscreenToggle' {
  declare module.exports: any;
}

declare module 'video-react/lib/components/control-bar/LoadProgressBar' {
  declare module.exports: any;
}

declare module 'video-react/lib/components/control-bar/MouseTimeDisplay' {
  declare module.exports: any;
}

declare module 'video-react/lib/components/control-bar/PlaybackRate' {
  declare module.exports: any;
}

declare module 'video-react/lib/components/control-bar/PlaybackRateMenuButton' {
  declare module.exports: any;
}

declare module 'video-react/lib/components/control-bar/PlayProgressBar' {
  declare module.exports: any;
}

declare module 'video-react/lib/components/control-bar/PlayToggle' {
  declare module.exports: any;
}

declare module 'video-react/lib/components/control-bar/ProgressControl' {
  declare module.exports: any;
}

declare module 'video-react/lib/components/control-bar/ReplayControl' {
  declare module.exports: any;
}

declare module 'video-react/lib/components/control-bar/SeekBar' {
  declare module.exports: any;
}

declare module 'video-react/lib/components/control-bar/VolumeMenuButton' {
  declare module.exports: any;
}

declare module 'video-react/lib/components/LoadingSpinner' {
  declare module.exports: any;
}

declare module 'video-react/lib/components/menu/Menu' {
  declare module.exports: any;
}

declare module 'video-react/lib/components/menu/MenuButton' {
  declare module.exports: any;
}

declare module 'video-react/lib/components/menu/MenuItem' {
  declare module.exports: any;
}

declare module 'video-react/lib/components/Player' {
  declare module.exports: any;
}

declare module 'video-react/lib/components/popup/Popup' {
  declare module.exports: any;
}

declare module 'video-react/lib/components/popup/PopupButton' {
  declare module.exports: any;
}

declare module 'video-react/lib/components/PosterImage' {
  declare module.exports: any;
}

declare module 'video-react/lib/components/Shortcut' {
  declare module.exports: any;
}

declare module 'video-react/lib/components/Slider' {
  declare module.exports: any;
}

declare module 'video-react/lib/components/Source' {
  declare module.exports: any;
}

declare module 'video-react/lib/components/time-controls/CurrentTimeDisplay' {
  declare module.exports: any;
}

declare module 'video-react/lib/components/time-controls/DurationDisplay' {
  declare module.exports: any;
}

declare module 'video-react/lib/components/time-controls/RemainingTimeDisplay' {
  declare module.exports: any;
}

declare module 'video-react/lib/components/time-controls/TimeDivider' {
  declare module.exports: any;
}

declare module 'video-react/lib/components/Video' {
  declare module.exports: any;
}

declare module 'video-react/lib/components/volume-control/VolumeBar' {
  declare module.exports: any;
}

declare module 'video-react/lib/components/volume-control/VolumeControl' {
  declare module.exports: any;
}

declare module 'video-react/lib/components/volume-control/VolumeLevel' {
  declare module.exports: any;
}

declare module 'video-react/lib' {
  declare module.exports: any;
}

declare module 'video-react/lib/Manager' {
  declare module.exports: any;
}

declare module 'video-react/lib/reducers' {
  declare module.exports: any;
}

declare module 'video-react/lib/reducers/operation' {
  declare module.exports: any;
}

declare module 'video-react/lib/reducers/player' {
  declare module.exports: any;
}

declare module 'video-react/lib/setupTests' {
  declare module.exports: any;
}

declare module 'video-react/lib/utils/browser' {
  declare module.exports: any;
}

declare module 'video-react/lib/utils/dom' {
  declare module.exports: any;
}

declare module 'video-react/lib/utils/fullscreen' {
  declare module.exports: any;
}

declare module 'video-react/lib/utils' {
  declare module.exports: any;
}

declare module 'video-react/lib/video-react' {
  declare module.exports: any;
}

// Filename aliases
declare module 'video-react/dist/video-react.cjs.js' {
  declare module.exports: $Exports<'video-react/dist/video-react.cjs'>;
}
declare module 'video-react/dist/video-react.es.js' {
  declare module.exports: $Exports<'video-react/dist/video-react.es'>;
}
declare module 'video-react/dist/video-react.full.js' {
  declare module.exports: $Exports<'video-react/dist/video-react.full'>;
}
declare module 'video-react/dist/video-react.full.min.js' {
  declare module.exports: $Exports<'video-react/dist/video-react.full.min'>;
}
declare module 'video-react/dist/video-react.js' {
  declare module.exports: $Exports<'video-react/dist/video-react'>;
}
declare module 'video-react/dist/video-react.min.js' {
  declare module.exports: $Exports<'video-react/dist/video-react.min'>;
}
declare module 'video-react/lib/actions/player.js' {
  declare module.exports: $Exports<'video-react/lib/actions/player'>;
}
declare module 'video-react/lib/actions/video.js' {
  declare module.exports: $Exports<'video-react/lib/actions/video'>;
}
declare module 'video-react/lib/components/Bezel.js' {
  declare module.exports: $Exports<'video-react/lib/components/Bezel'>;
}
declare module 'video-react/lib/components/BigPlayButton.js' {
  declare module.exports: $Exports<'video-react/lib/components/BigPlayButton'>;
}
declare module 'video-react/lib/components/ClickableComponent.js' {
  declare module.exports: $Exports<'video-react/lib/components/ClickableComponent'>;
}
declare module 'video-react/lib/components/control-bar/ClosedCaptionButton.js' {
  declare module.exports: $Exports<'video-react/lib/components/control-bar/ClosedCaptionButton'>;
}
declare module 'video-react/lib/components/control-bar/ControlBar.js' {
  declare module.exports: $Exports<'video-react/lib/components/control-bar/ControlBar'>;
}
declare module 'video-react/lib/components/control-bar/ForwardControl.js' {
  declare module.exports: $Exports<'video-react/lib/components/control-bar/ForwardControl'>;
}
declare module 'video-react/lib/components/control-bar/ForwardReplayControl.js' {
  declare module.exports: $Exports<'video-react/lib/components/control-bar/ForwardReplayControl'>;
}
declare module 'video-react/lib/components/control-bar/FullscreenToggle.js' {
  declare module.exports: $Exports<'video-react/lib/components/control-bar/FullscreenToggle'>;
}
declare module 'video-react/lib/components/control-bar/LoadProgressBar.js' {
  declare module.exports: $Exports<'video-react/lib/components/control-bar/LoadProgressBar'>;
}
declare module 'video-react/lib/components/control-bar/MouseTimeDisplay.js' {
  declare module.exports: $Exports<'video-react/lib/components/control-bar/MouseTimeDisplay'>;
}
declare module 'video-react/lib/components/control-bar/PlaybackRate.js' {
  declare module.exports: $Exports<'video-react/lib/components/control-bar/PlaybackRate'>;
}
declare module 'video-react/lib/components/control-bar/PlaybackRateMenuButton.js' {
  declare module.exports: $Exports<'video-react/lib/components/control-bar/PlaybackRateMenuButton'>;
}
declare module 'video-react/lib/components/control-bar/PlayProgressBar.js' {
  declare module.exports: $Exports<'video-react/lib/components/control-bar/PlayProgressBar'>;
}
declare module 'video-react/lib/components/control-bar/PlayToggle.js' {
  declare module.exports: $Exports<'video-react/lib/components/control-bar/PlayToggle'>;
}
declare module 'video-react/lib/components/control-bar/ProgressControl.js' {
  declare module.exports: $Exports<'video-react/lib/components/control-bar/ProgressControl'>;
}
declare module 'video-react/lib/components/control-bar/ReplayControl.js' {
  declare module.exports: $Exports<'video-react/lib/components/control-bar/ReplayControl'>;
}
declare module 'video-react/lib/components/control-bar/SeekBar.js' {
  declare module.exports: $Exports<'video-react/lib/components/control-bar/SeekBar'>;
}
declare module 'video-react/lib/components/control-bar/VolumeMenuButton.js' {
  declare module.exports: $Exports<'video-react/lib/components/control-bar/VolumeMenuButton'>;
}
declare module 'video-react/lib/components/LoadingSpinner.js' {
  declare module.exports: $Exports<'video-react/lib/components/LoadingSpinner'>;
}
declare module 'video-react/lib/components/menu/Menu.js' {
  declare module.exports: $Exports<'video-react/lib/components/menu/Menu'>;
}
declare module 'video-react/lib/components/menu/MenuButton.js' {
  declare module.exports: $Exports<'video-react/lib/components/menu/MenuButton'>;
}
declare module 'video-react/lib/components/menu/MenuItem.js' {
  declare module.exports: $Exports<'video-react/lib/components/menu/MenuItem'>;
}
declare module 'video-react/lib/components/Player.js' {
  declare module.exports: $Exports<'video-react/lib/components/Player'>;
}
declare module 'video-react/lib/components/popup/Popup.js' {
  declare module.exports: $Exports<'video-react/lib/components/popup/Popup'>;
}
declare module 'video-react/lib/components/popup/PopupButton.js' {
  declare module.exports: $Exports<'video-react/lib/components/popup/PopupButton'>;
}
declare module 'video-react/lib/components/PosterImage.js' {
  declare module.exports: $Exports<'video-react/lib/components/PosterImage'>;
}
declare module 'video-react/lib/components/Shortcut.js' {
  declare module.exports: $Exports<'video-react/lib/components/Shortcut'>;
}
declare module 'video-react/lib/components/Slider.js' {
  declare module.exports: $Exports<'video-react/lib/components/Slider'>;
}
declare module 'video-react/lib/components/Source.js' {
  declare module.exports: $Exports<'video-react/lib/components/Source'>;
}
declare module 'video-react/lib/components/time-controls/CurrentTimeDisplay.js' {
  declare module.exports: $Exports<'video-react/lib/components/time-controls/CurrentTimeDisplay'>;
}
declare module 'video-react/lib/components/time-controls/DurationDisplay.js' {
  declare module.exports: $Exports<'video-react/lib/components/time-controls/DurationDisplay'>;
}
declare module 'video-react/lib/components/time-controls/RemainingTimeDisplay.js' {
  declare module.exports: $Exports<'video-react/lib/components/time-controls/RemainingTimeDisplay'>;
}
declare module 'video-react/lib/components/time-controls/TimeDivider.js' {
  declare module.exports: $Exports<'video-react/lib/components/time-controls/TimeDivider'>;
}
declare module 'video-react/lib/components/Video.js' {
  declare module.exports: $Exports<'video-react/lib/components/Video'>;
}
declare module 'video-react/lib/components/volume-control/VolumeBar.js' {
  declare module.exports: $Exports<'video-react/lib/components/volume-control/VolumeBar'>;
}
declare module 'video-react/lib/components/volume-control/VolumeControl.js' {
  declare module.exports: $Exports<'video-react/lib/components/volume-control/VolumeControl'>;
}
declare module 'video-react/lib/components/volume-control/VolumeLevel.js' {
  declare module.exports: $Exports<'video-react/lib/components/volume-control/VolumeLevel'>;
}
declare module 'video-react/lib/index' {
  declare module.exports: $Exports<'video-react/lib'>;
}
declare module 'video-react/lib/index.js' {
  declare module.exports: $Exports<'video-react/lib'>;
}
declare module 'video-react/lib/Manager.js' {
  declare module.exports: $Exports<'video-react/lib/Manager'>;
}
declare module 'video-react/lib/reducers/index' {
  declare module.exports: $Exports<'video-react/lib/reducers'>;
}
declare module 'video-react/lib/reducers/index.js' {
  declare module.exports: $Exports<'video-react/lib/reducers'>;
}
declare module 'video-react/lib/reducers/operation.js' {
  declare module.exports: $Exports<'video-react/lib/reducers/operation'>;
}
declare module 'video-react/lib/reducers/player.js' {
  declare module.exports: $Exports<'video-react/lib/reducers/player'>;
}
declare module 'video-react/lib/setupTests.js' {
  declare module.exports: $Exports<'video-react/lib/setupTests'>;
}
declare module 'video-react/lib/utils/browser.js' {
  declare module.exports: $Exports<'video-react/lib/utils/browser'>;
}
declare module 'video-react/lib/utils/dom.js' {
  declare module.exports: $Exports<'video-react/lib/utils/dom'>;
}
declare module 'video-react/lib/utils/fullscreen.js' {
  declare module.exports: $Exports<'video-react/lib/utils/fullscreen'>;
}
declare module 'video-react/lib/utils/index' {
  declare module.exports: $Exports<'video-react/lib/utils'>;
}
declare module 'video-react/lib/utils/index.js' {
  declare module.exports: $Exports<'video-react/lib/utils'>;
}
declare module 'video-react/lib/video-react.js' {
  declare module.exports: $Exports<'video-react/lib/video-react'>;
}
