// flow-typed signature: 3a3bcd9cf8e3789fb656e2a4d13a9c34
// flow-typed version: <<STUB>>/@zeit/next-source-maps_v^0.0.3/flow_v0.83.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@zeit/next-source-maps'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@zeit/next-source-maps' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module '@zeit/next-source-maps/index' {
  declare module.exports: $Exports<'@zeit/next-source-maps'>;
}
declare module '@zeit/next-source-maps/index.js' {
  declare module.exports: $Exports<'@zeit/next-source-maps'>;
}
